import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient();
  const {data: {user}, error} = await supabase.auth.getUser();

  // set the nav bar depending on if the user is logged in or not
  const authsection = user && !error ? (
    <Link href="/dashboard" className="text-sm text-gray-500 hover:text-gray-700">
        {user?.email}
    </Link>
  ) : (
    <>
      <Link href="/login" className="text-sm text-gray-500 hover:text-gray-700">
        Login
      </Link>
      <Link href="/signup" className="ml-4 text-sm text-gray-500 hover:text-gray-700">
          Sign Up
      </Link>
    </>
  );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 border-b justify-between items-center flex">
          {/* put logo here */}
          <Link href="/" className="text-2xl font-bold">Starter Project</Link>

          <nav>
            {authsection}
          </nav>

        </header>
        {children}
      </body>
    </html>
  );
}
